default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: '021426'
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>

development:
  <<: *default
  database: tasks_api_development

test:
  <<: *default
  database: tasks_api_test

production:
  <<: *default
  database: tasks_api_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
